### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by kaijieshi7** [vinbigdata-medical/MIDL2021-VinDr-RibCXR#2]
Why don't check your code carefully, there so many bugs............

**Comment by levi3001** [comment]
Can you show me what kind of bugs you get?

**Comment by kaijieshi7** [comment]
okok

1. in `cvcore/tools/vaild_tools.py` about 31-th row, `best_metric` always is None, so it can't directly print.
2. in `cvcore/tools/multi_rib_dataset.py` about 72-nd row, it's better add `num_workers=cfg.SYSTEM.NUM_WORKERS` for accelerate.
3. Directly put downloaded data into `data` cannot run in my computer, so i use absolute address(chinese, may not be accurate).
4. It's dump in second epoch, i'm trying to fix it.

**Comment by kaijieshi7** [comment]
![Screenshot from 2022-04-07 14-00-15](https://user-images.githubusercontent.com/19171201/162130532-9618db38-da45-4271-9709-d9457802f0f6.png)
It's the fourth problem as mentiond above

**Comment by levi3001** [comment]
for 3, I think that there is some confuse in our document, the data should be outside cvcore, the cvcore/data is for dataloader and I put data outside cvcore for dataset itself (the link in my config is data/train/etc)
For 1, I will check why it dont print the best_metric and for 4 I will check the code again, it seems like the bug in 4 is not happend in every run since you can complete 1 epochs without any error

**Comment by kaijieshi7** [comment]
okok, better github work can get more cite.

**Comment by kaijieshi7** [comment]
One more, the file name of downloaded data is different from default name in yaml file.

**Comment by kaijieshi7** [comment]
One more, there is a bug in 27-th row of `cvcore/tools/vaild_tool.py`. I have refine it by myself.
